language: node_js
node_js:
  - "stable"
install:
  - npm i -g yarn
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn style
  - yarn test
after_failure:
  - "cat /home/travis/builds/Cosium/dry-dry/yarn-error.log"
